# Generated by Django 2.1.2 on 2018-10-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='media_choice',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='unknown', max_length=8),
        ),
    ]
