# Generated by Django 2.1.2 on 2018-10-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_auto_20181017_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], db_column='IF', default='FR', max_length=2),
        ),
    ]
